version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  ts_webservice:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ts_webservice_im
    container_name: ts_webservice_ctr
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start
